pipeline {
    agent any

    stages {

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t server-monitor -f docker/Dockerfile .'
            }
        }

        stage('Remove Old Container') {
            steps {
                sh '''
                docker stop server-monitor || true
                docker rm server-monitor || true
                '''
            }
        }

        stage('Deploy Container') {
            steps {
                sh '''
                docker run -d \
                --name server-monitor \
                -p 5000:5000 \
                server-monitor
                '''
            }
        }
    }
}