pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                url: 'https://github.com/YOUR_USERNAME/server-health-monitor.git'
            }
        }

        stage('Build Image') {
            steps {
                sh 'docker build -t server-monitor -f docker/Dockerfile .'
            }
        }

        stage('Stop Old Container') {
            steps {
                sh '''
                docker stop server-monitor || true
                docker rm server-monitor || true
                '''
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                docker run -d \
                --name server-monitor \
                -p 5000:5000 \
                server-monitor
                '''
            }
        }
    }
}